# Generated by Django 3.0.2 on 2020-01-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservering', '0002_customer_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stylist',
            fields=[
                ('stylist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
    ]
