# Generated by Django 3.0.2 on 2020-01-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservering', '0003_stylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(default='000000001', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
